from .especialidadserializer import Especialidadserializer
from .familiaresserializer   import Familiaresserializer 
from .historiaClinicaserializer import historiaClinicaserializer
from .pacientesserializer import Pacientesserializer
from .perfiluserserializer import Perfiluserserializer
from .personalSaludserializer import Personal_saludserializer
from .signosvitalesserializer import Signosvitalesserializer
from .usuarioserializer import Usuarioserializer