# Generated by Django 4.1.1 on 2022-09-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('ID_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=30, verbose_name='especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('Cedula_Fliar', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('TipoID', models.CharField(max_length=10, verbose_name='tipo')),
                ('Nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('Apellido', models.CharField(max_length=30, verbose_name='apell')),
                ('Parentezco', models.CharField(max_length=30, verbose_name='flia')),
                ('Genero', models.CharField(max_length=30, verbose_name='sexo')),
                ('Celular', models.CharField(max_length=10, verbose_name='cel')),
                ('Direccion', models.CharField(max_length=30, verbose_name='dir')),
                ('Municipio', models.CharField(max_length=30, verbose_name='muni')),
                ('Departamento', models.CharField(max_length=30, verbose_name='dpto')),
                ('Email', models.EmailField(max_length=100, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='historiaClinica',
            fields=[
                ('ID_HistC', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnostico', models.CharField(max_length=200, verbose_name='diagnos')),
                ('Examen_Fisico', models.CharField(max_length=200, verbose_name='examen')),
                ('Sugerencias', models.CharField(max_length=200, verbose_name='sug')),
                ('Evolucion', models.CharField(max_length=200, verbose_name='evol')),
            ],
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('ID_Perfil', models.AutoField(primary_key=True, serialize=False)),
                ('Perfil', models.CharField(max_length=30, verbose_name='perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30, verbose_name='username')),
                ('Password', models.CharField(max_length=30, verbose_name='passw')),
                ('ID_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='authApp.perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Signosvitales',
            fields=[
                ('ID_Signos', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Fre_Cardiaca', models.IntegerField()),
                ('Fre_Respiratoria', models.IntegerField()),
                ('Pre_Arterial', models.IntegerField()),
                ('Temperatura', models.IntegerField()),
                ('Oximetria', models.IntegerField()),
                ('Glicemia', models.IntegerField()),
                ('ID_HistC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signosvitales', to='authApp.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Salud',
            fields=[
                ('cedulaPS', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('Apellido', models.CharField(max_length=30, verbose_name='apell')),
                ('Genero', models.CharField(max_length=30, verbose_name='sexo')),
                ('regMedico', models.CharField(max_length=10, verbose_name='registro')),
                ('Celular', models.CharField(max_length=10, verbose_name='cel')),
                ('Email', models.EmailField(max_length=100, verbose_name='email')),
                ('ID_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personaSalud', to='authApp.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('Cedula_Paciente', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Nombres', models.CharField(max_length=30, verbose_name='nombre')),
                ('Apellidos', models.CharField(max_length=30, verbose_name='apell')),
                ('Fecha_Nac', models.DateField(max_length=20, verbose_name='fechanac')),
                ('Genero', models.CharField(max_length=30, verbose_name='sexo')),
                ('Celular', models.CharField(max_length=10, verbose_name='cel')),
                ('Telefono', models.CharField(max_length=10, verbose_name='tel')),
                ('Direccion', models.CharField(max_length=10, verbose_name='dire')),
                ('Latitud', models.CharField(max_length=20, verbose_name='lat')),
                ('Longitud', models.CharField(max_length=20, verbose_name='long')),
                ('Ciudad', models.CharField(max_length=20, verbose_name='ciudad')),
                ('Departamento', models.CharField(max_length=20, verbose_name='depar')),
                ('Email', models.EmailField(max_length=100, verbose_name='email')),
                ('Cedula_Fliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pacientes', to='authApp.familiares')),
                ('cedulaPS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pacientes', to='authApp.personal_salud')),
            ],
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='CedulaPS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaClinica', to='authApp.personal_salud'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='Cedula_Fliar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaClinica', to='authApp.familiares'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='Cedula_Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaClinica', to='authApp.pacientes'),
        ),
    ]
