from .Usuarioview import CrearUsuarioView
from .Usuarioview import UsuarioView
from .personalSaludview import CrearPersonalSaludView
from .personalSaludview import PersonalSaludView
from .familiaresview import CrearFamiliaresView
from .familiaresview import FamiliaresView
from .historiaClinicaviews import CrearHistoriaClinicaView
from .historiaClinicaviews import HistoriaClinicaView
from .pacientesview import CrearPacientesView
from .pacientesview import PacientesView
from .signosvitalesview import CrearSignosVitalesView
from .signosvitalesview import SignosVitalesView